# Generated by Django 4.0.2 on 2022-02-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='balance')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('transitions_amount', models.IntegerField(verbose_name='transition')),
                ('orders_amount', models.IntegerField(verbose_name='orders_amount')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='partners.partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='main.product')),
            ],
        ),
    ]
