# Generated by Django 4.0.2 on 2022-02-13 17:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category')),
                ('description', models.TextField(verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.IntegerField(verbose_name='sku')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('meta_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='product/%b%d%Y%H%M%S/'), size=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='datetime')),
                ('status', models.CharField(max_length=15, verbose_name='status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='mark')),
                ('text', models.TextField(verbose_name='text')),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='feedback/%b%d%Y%H%M%S/'), size=None)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('amount', models.IntegerField(verbose_name='amount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='main.product')),
            ],
        ),
    ]
