# Generated by Django 4.0.2 on 2022-02-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='feedback_reply')),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.feedback')),
            ],
        ),
    ]
