# Generated by Django 4.0.2 on 2022-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedbackreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.IntegerField(unique=True, verbose_name='sku'),
        ),
    ]
