# Generated by Django 4.0.2 on 2022-02-13 18:27

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='photos',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.ImageField(upload_to='feedback/%b%d%Y%H%M%S/'), size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.ImageField(upload_to='product/%b%d%Y%H%M%S/'), size=None),
        ),
    ]
