# Generated by Django 4.0.2 on 2022-02-13 18:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feedback_photos_alter_product_meta_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='feedback/%b%d%Y%H%M%S/'), size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='product/%b%d%Y%H%M%S/'), size=None),
        ),
    ]
