# Generated by Django 4.0.2 on 2022-02-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_feedback_photos_alter_product_meta_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
    ]
