# Generated by Django 4.0.2 on 2022-02-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_feedback_photos_productimage_feedbackimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackimage',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_image', to='main.feedbackimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='main.productimage'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='https://ecommerceapi.s3.amazonaws.com/static/no_avatar.png', upload_to='product/%b%d%Y%H%M%S/'),
        ),
    ]
