# Generated by Django 4.0.2 on 2022-02-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_feedback_image_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='similar_to', to='main.Product'),
        ),
    ]
