# Generated by Django 4.0.2 on 2022-02-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_similar_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='similar_to',
            field=models.ManyToManyField(blank=True, to='main.Product'),
        ),
    ]
