# Generated by Django 4.0.2 on 2022-02-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_similar_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='small_image',
            field=models.ImageField(default='https://ecommerceapi.s3.amazonaws.com/static/no_avatar.png', upload_to='product/resized/%b%d%Y%H%M%S/'),
        ),
    ]
